version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus_cont
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
